(function(g){'use strict';
 const cfg=g.HISTORY_API_CONFIG||{},personal=!/\/(teacher|board)\.html$/.test(location.pathname),storeKey='history-v42-'+(personal?'student':'teacher')+(cfg.mode==='supabase-rc'?':rc:'+encodeURIComponent(cfg.rcUrl||'unconfigured')+':'+encodeURIComponent(cfg.rcStorageScope||'default'):(cfg.gasUrl?':'+encodeURIComponent(cfg.gasUrl):'')),ticketKey=storeKey+':ticket',pending=new Map();let ticket=null,bootstrapData=null,clockOffset=0,frame=null,bridgeWindow=null,bridgeOrigin='',channel='',bootstrapPromise=null;
 const persistent={get(){try{return personal?localStorage.getItem(storeKey):null}catch{return null}},set(s){try{if(personal){if(s?.role==='student'&&!s.testOnly&&s.rememberDevice===true)localStorage.setItem(storeKey,JSON.stringify(s));else localStorage.removeItem(storeKey)}}catch{}}};
 let session;try{session=JSON.parse(sessionStorage.getItem(storeKey)||persistent.get()||'null');if(session?.expiresAt&&Date.parse(session.expiresAt)<=Date.now()){session=null;sessionStorage.removeItem(storeKey);persistent.set(null)}}catch{session=null}
 const touchEnabled=personal&&cfg.sessionTouchEnabled===true;
 const touchIntervalMs=300000;
 let touchTimer=null,touchFlight=null,touchDueAt=0,touchFailures=0;
 try{const cached=JSON.parse(sessionStorage.getItem(ticketKey)||'null');if(cached?.data?.ticket?.expiresAt>Date.now()+(Number(cached.clockOffset)||0)+10000){bootstrapData=cached.data;ticket=cached.data.ticket;clockOffset=Number(cached.clockOffset)||0}else sessionStorage.removeItem(ticketKey)}catch{sessionStorage.removeItem(ticketKey)}
 const applyCopyright=x=>{const v=x?.copyright||x?.publicDisplay?.copyright||x?.authority3?.copyright;if(v&&g.HistoryCopyright)g.HistoryCopyright.apply(v)};
 const uuid=()=>crypto.randomUUID?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(20)),x=>x.toString(16).padStart(2,'0')).join('');
 function remember(s){const changed=session?.token!==s?.token||JSON.stringify(session?.context3)!==JSON.stringify(s?.context3);session=s;if(changed)sessionStorage.removeItem(storeKey+':pending');if(s)sessionStorage.setItem(storeKey,JSON.stringify(s));else{sessionStorage.removeItem(storeKey);sessionStorage.removeItem(storeKey+':pending')}if(!s?.testOnly)persistent.set(s);if(changed){touchFailures=0;scheduleTouch(s?.serverNow||Date.now());}if(changed&&g.dispatchEvent&&typeof CustomEvent==='function')g.dispatchEvent(new CustomEvent('history-session-changed',{detail:{authenticated:!!s}}))}
 addEventListener('storage',e=>{if(personal&&e.key===storeKey&&!session?.testOnly){let s=null;try{s=JSON.parse(e.newValue||'null')}catch{}remember(s)}});
 const readActions=new Set(['cards.openings.list','cards.openings.read','collection.read','missions.read','student.records.read','completion.reward.status','teacher.records.read','teacher.records.student','teacher.records.csv','teacher.records.settings','teacher.board.read','student.state','rankings.read','portal.read','access.check','teacher.overview','teacher.student.cards','teacher.test.check','student.login','teacher.login','owner.recover','owner.overview','teacher.scope.read','teacher.devices.read','teacher.testSettings.read','session.logout','session.touch']);
 const atomicCompletionActions=new Set(['attempt.answer','attempt.advance','attempt.order','attempt.match','attempt.match.complete','attempt.quiz.complete','attempt.board.submit']);
 function pendingRequest(action,payload,requestId){if(readActions.has(action))return{requestId:requestId||uuid(),clear(){}};let rows;try{rows=JSON.parse(sessionStorage.getItem(storeKey+':pending')||'[]')}catch{rows=[]}rows=rows.filter(r=>r.owner===session?.token);const fingerprint=JSON.stringify({action,payload}),old=rows.find(r=>r.fingerprint===fingerprint),id=requestId||old?.requestId||uuid();if(!old){rows.push({fingerprint,requestId:id,owner:session?.token});sessionStorage.setItem(storeKey+':pending',JSON.stringify(rows))}return{requestId:id,clear(){let current;try{current=JSON.parse(sessionStorage.getItem(storeKey+':pending')||'[]')}catch{current=[]}sessionStorage.setItem(storeKey+':pending',JSON.stringify(current.filter(r=>r.requestId!==id)))}}}
 function sendPending(){if(!bridgeWindow)return;for(const [callId,p]of pending)if(!p.sent){p.sent=true;bridgeWindow.postMessage({type:'history-api',channel,callId,request:p.request},bridgeOrigin)}}
 function bridge(req){return new Promise((resolve,reject)=>{if(!/^https:\/\/script\.google\.com\/macros\/s\/[\w-]+\/exec$/.test(cfg.gasUrl||'')){const e=Error('Code.gs TEST 웹앱의 /exec 주소를 config.js에 설정하거나 로컬 시험 서버로 열어 주세요.');e.code='CONFIG_REQUIRED';return reject(e)}if(!frame){channel=uuid();frame=document.createElement('iframe');frame.hidden=true;frame.src=cfg.gasUrl+'?page=bridge&channel='+encodeURIComponent(channel);document.body.append(frame)}const callId=uuid(),timeout=setTimeout(()=>{pending.delete(callId);reject(Error('연결 시간 초과: 허용 출처와 TEST 웹앱 배포 설정을 확인하세요.'))},20000);pending.set(callId,{request:req,sent:false,resolve:x=>{clearTimeout(timeout);resolve(x)},reject});sendPending()})}
 addEventListener('message',e=>{if(!frame||(!/^https:\/\/([\w-]+\.)?googleusercontent\.com$/.test(e.origin)&&e.origin!=='https://script.google.com'))return;const d=e.data;if(d?.channel!==channel)return;if(d.type==='history-bridge-ready'&&!bridgeWindow){bridgeWindow=e.source;bridgeOrigin=e.origin;sendPending();return}if(e.source!==bridgeWindow||e.origin!==bridgeOrigin)return;if(d.type==='history-api-result'&&pending.has(d.callId)){pending.get(d.callId).resolve(d.result);pending.delete(d.callId)}});
 async function rcTransport(req,timeoutMs=20000){
  let endpoint;try{endpoint=new URL(cfg.rcUrl);if(endpoint.protocol!=='https:'||endpoint.username||endpoint.password||endpoint.search||endpoint.hash||!(endpoint.pathname==='/functions/v1/history-normal-rc-api'||endpoint.hostname==='thwbtfkrbpxhefrtyavu.supabase.co'&&endpoint.pathname==='/functions/v1/history-classroom-rc'))throw Error();}catch{const e=Error('RC 전용 config.rc.js에 승인된 학생 RC HTTPS 주소를 설정하세요.');e.code='CONFIG_REQUIRED';throw e}
  if(cfg.rcRegion==='ap-northeast-2')endpoint.searchParams.set('forceFunctionRegion',cfg.rcRegion);
  const started=performance.now(),metrics=cfg.mode==='supabase-rc'&&new URLSearchParams(location.search).get('rcMetrics')==='1';let resultCode='NETWORK_ERROR',responseBytes=0,serverTiming='';
  const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),timeoutMs);
  try{const response=await fetch(endpoint.href,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(req),signal:abort.signal,credentials:'omit',cache:'no-store',redirect:'error'});const raw=await response.text();if(metrics){responseBytes=new TextEncoder().encode(raw).length;serverTiming=response.headers.get('server-timing')||'';}const body=JSON.parse(raw);resultCode=body?.ok?'OK':body?.code||'INVALID_RESPONSE';if(!body||typeof body.ok!=='boolean'||(!body.ok&&typeof body.code!=='string'))throw Error('INVALID_API_RESPONSE');return body}finally{clearTimeout(timer);if(metrics)console.info('RC_METRIC '+JSON.stringify({action:req.action,durationMs:Math.round(performance.now()-started),responseBytes,serverTiming,code:resultCode}))}
 }
 async function transport(req,timeoutMs=20000){if(cfg.mode==='supabase-rc')return rcTransport(req,timeoutMs);if(cfg.mode==='local'||['localhost','127.0.0.1'].includes(location.hostname)){const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),timeoutMs);try{const r=await fetch('/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(req),signal:abort.signal});return await r.json()}finally{clearTimeout(timer)}}return bridge(req)}
 async function bootstrap(){if(bootstrapData&&ticket&&ticket.expiresAt>Date.now()+clockOffset+10000)return bootstrapData;if(bootstrapPromise)return bootstrapPromise;bootstrapPromise=(async()=>{const r=await transport({action:'public.bootstrap'});if(!r.ok)throw Error(r.message||r.code);bootstrapData=r.data;ticket=r.data.ticket;clockOffset=r.data.serverNow-Date.now();sessionStorage.setItem(ticketKey,JSON.stringify({data:bootstrapData,clockOffset}));applyCopyright(r.data);return r.data})();try{return await bootstrapPromise}finally{bootstrapPromise=null}}
  async function requestNow(action,payload={},opts={}){if(session?.role==='student'&&session.context3&&action==='student.records.read')payload={...payload,context3:session.context3};if(session?.context3&&['teacher','owner'].includes(session.role)&&(action.startsWith('teacher.')&&action!=='teacher.login'||['rankings.read','portal.read'].includes(action)))payload={...payload,context3:payload.context3||{...session.context3,schoolYear:payload.schoolYear||session.context3.schoolYear}};const owner=session?.token,scopeAtStart=JSON.stringify(session?.context3),authToken=opts.token||owner,record=pendingRequest(action,payload,opts.requestId),requestId=record.requestId,maxAttempts=Math.max(1,Math.min(5,Number(opts.maxAttempts)||3)),timeoutMs=Math.max(3000,Math.min(25000,Number(opts.timeoutMs)||20000)),retryable=new Set(['BUSY','CONNECTION_ERROR','SERVER_ERROR']);let error;for(let attempt=0;attempt<maxAttempts;attempt++){try{if(!ticket||ticket.expiresAt<Date.now()+clockOffset+10000)await bootstrap();const completionAuthHint=cfg.atomicCompletionEnabled===true&&atomicCompletionActions.has(action)?session?.completionAuthHint:null;const r=await transport({action,payload,requestId,ticket,token:authToken,...(completionAuthHint?{completionAuthHint}:{})},timeoutMs);if(!action.endsWith('.login')&&(session?.token!==owner||JSON.stringify(session?.context3)!==scopeAtStart)){const changed=Error('로그인 계정이 변경되었습니다. 다시 확인하세요.');changed.code='SESSION_CHANGED';throw changed}if(r.ok){record.clear();applyCopyright(r.data);if(action==='student.state'&&r.data?.completionAuthHint&&session?.token===owner)remember({...session,completionAuthHint:r.data.completionAuthHint});return r.data}if(r.code==='REQUEST_EXPIRED'){ticket=null;bootstrapData=null;sessionStorage.removeItem(ticketKey);continue}const failed=Error(r.message||r.code);failed.code=r.code;failed.data=r.data;failed.retryable=retryable.has(r.code);throw failed}catch(e){error=e;if(e.code&&!e.retryable){record.clear();if(['SESSION_EXPIRED','AUTH_REQUIRED','SESSION_REVOKED'].includes(e.code)&&session?.token===owner)remember(null);break}if(attempt+1<maxAttempts)await new Promise(r=>setTimeout(r,900*2**attempt+Math.random()*600))}}if(error?.code)throw error;const connection=Error('서버에 연결하지 못했습니다. 연결을 확인한 뒤 같은 작업을 다시 시도해 주세요.');connection.code='CONNECTION_ERROR';throw connection}
 let studentMutationTail=Promise.resolve();const singleFlight=new Map(),loginFlights=new Map();
 function request(action,payload={},opts={}){const run=()=>requestNow(action,payload,opts),student=session?.role==='student'&&!session?.testOnly;if(student&&['student.state','collection.read','missions.read','student.records.read','completion.reward.status','cards.openings.list','cards.openings.read','rankings.read'].includes(action)){const key=action+':'+JSON.stringify(payload);if(singleFlight.has(key))return singleFlight.get(key);const task=run().finally(()=>singleFlight.delete(key));singleFlight.set(key,task);return task}if(student&&!readActions.has(action)){const task=studentMutationTail.then(run,run);studentMutationTail=task.catch(()=>{});return task}return run()}
 function touchEligible(){return touchEnabled&&session?.role==='student'&&!session.testOnly&&(!session.expiresAt||Date.parse(session.expiresAt)>Date.now())}
 function scheduleTouch(lastActivity){clearTimeout(touchTimer);touchTimer=null;if(!touchEligible())return;const activity=Number(lastActivity)||Date.now();touchDueAt=activity+(session?.serverNow===activity?-clockOffset:0)+touchIntervalMs;armTouch()}
 function armTouch(){clearTimeout(touchTimer);touchTimer=null;if(!touchEligible()||document.hidden||touchFailures>=2)return;touchTimer=setTimeout(()=>void touchWhenDue(),Math.max(0,touchDueAt-Date.now()))}
 async function touchWhenDue(){if(!touchEligible()||document.hidden||touchFlight)return;if(Date.now()<touchDueAt){armTouch();return}const owner=session.token;touchFlight=request('session.touch',{}, {maxAttempts:1,timeoutMs:10000}).then(out=>{if(session?.token!==owner)return;touchFailures=0;const serverDue=Date.parse(out?.nextDueAt||'');touchDueAt=Number.isFinite(serverDue)?Math.max(Date.now()+1000,serverDue-clockOffset+1000):Date.now()+touchIntervalMs;armTouch()}).catch(()=>{if(session?.token!==owner)return;touchFailures++;touchDueAt=Date.now()+touchIntervalMs;armTouch()}).finally(()=>{touchFlight=null});return touchFlight}
 if(touchEnabled){document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(touchTimer);touchTimer=null}else{touchFailures=0;armTouch()}});addEventListener('pagehide',()=>{clearTimeout(touchTimer);touchTimer=null});scheduleTouch(session?.serverNow||0)}
 async function login(role,p){const run=async()=>{const result=await request(role+'.login',p,role==='student'?{maxAttempts:2,timeoutMs:10000}:{maxAttempts:2});remember(result);if(role==='student'&&!result.student){g.dispatchEvent(new CustomEvent('history-login-verified'));const initial=await request('attendance.claim',{},{maxAttempts:2,timeoutMs:10000});result.student=initial.student;result.attendance={claimed:!!initial.claimed,result:initial.result||null}}return result};if(role!=='student')return run();const key=JSON.stringify(p);if(loginFlights.has(key))return loginFlights.get(key);const task=run();loginFlights.set(key,task);try{return await task}finally{loginFlights.delete(key)}}
 g.HistoryGameAPI={version:'4.9',get session(){return session},request,bootstrap,login,async logout(){try{await request('session.logout')}finally{remember(null)}},clear:()=>remember(null),resolveRequest(requestId){let rows;try{rows=JSON.parse(sessionStorage.getItem(storeKey+':pending')||'[]')}catch{rows=[]}sessionStorage.setItem(storeKey+':pending',JSON.stringify(rows.filter(r=>r.owner!==session?.token||r.requestId!==requestId)))},saveSession:remember,newRequestId:uuid};
})(window);
