/* This entry point never calls teacher.overview or downloads the class roster. */
(function(){'use strict';
const API=HistoryGameAPI,U=ReportUI27,root=document.querySelector('#boardApp27');
let data=null,selected=0,refreshTimer=null,rotateTimer=null,pending=false,error='',rotationPaused=false,rankingScope='class',rankingLimit=10;
let filter={schoolYear:API.session?.user.schoolYear||2026,...(API.session?.context3?.grade?{grade:API.session.context3.grade,classNo:API.session.context3.classNo}:{})};

function stop(){clearTimeout(refreshTimer);clearInterval(rotateTimer)}
function armRotation(){clearInterval(rotateTimer);if(!data?.settings?.rotateSeconds||rotationPaused)return;rotateTimer=setInterval(()=>{if(!document.hidden&&data?.panels?.length){selected=(selected+1)%data.panels.length;render()}},data.settings.rotateSeconds*1000)}
function login(){stop();data=null;root.innerHTML=`<section class="panel login"><h1>교실 학습 전광판</h1><p>인증된 교사만 열 수 있습니다. 학생 명부는 이 화면으로 보내지 않습니다.</p><form id="boardLogin27"><label>학교<select name="schoolId" id="boardSchool3"><option value="">학교 불러오는 중</option></select></label><label>학년도<input name="schoolYear" type="number" value="2026" required></label><label>교사 아이디<input name="loginId" autocomplete="username" required></label><label>교사 접속 코드<input name="code" type="password" autocomplete="current-password" required></label><button>전광판 로그인</button></form><p role="status">${U.esc(error)}</p></section>`;document.querySelector('#boardLogin27').onsubmit=async e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));p.schoolYear=+p.schoolYear;try{await API.login('teacher',p);filter={schoolYear:p.schoolYear,...(API.session?.context3?.grade?{grade:API.session.context3.grade,classNo:API.session.context3.classNo}:{})};error='';await load()}catch(e){error=e.message;login()}};API.bootstrap().then(b=>{const s=document.querySelector('#boardSchool3'),labels=window.HISTORY_API_CONFIG?.schoolLabels||{};if(s)s.innerHTML=(b.schools||[]).map(x=>'<option value="'+U.esc(x.id)+'">'+U.esc(labels[x.id]||x.name)+'</option>').join('')||'<option value="">학교 사용 준비가 필요합니다</option>';}).catch(e=>{error=e.message;});}

function rankingMarkup(d){const scopes=d?.scopes||{};if(!scopes[rankingScope]?.available)rankingScope=scopes.grade?.available?'grade':'year';const current=scopes[rankingScope]||{label:'순위',rows:[],available:false};const buttons=['class','grade','year','all'].map(key=>{const x=scopes[key]||{};return `<button type="button" class="${rankingScope===key?'active':''}" data-rank-scope="${key}" ${x.available?'':'disabled'}>${U.esc(x.label||key)}</button>`}).join('');const rows=(current.rows||[]).map(r=>`<tr><td>${r.rank}</td><td>${U.esc(r.displayName||'')}</td><td>${U.esc(rankingScope==='all'?r.schoolYear+'학년도 · '+r.grade+'학년 '+r.classNo+'반 '+r.number+'번':rankingScope==='year'?r.grade+'학년 '+r.classNo+'반 '+r.number+'번':rankingScope==='grade'?r.classNo+'반 '+r.number+'번':r.number+'번')}</td><td>${Number(r.score||0).toLocaleString()} XP</td></tr>`).join('');return `<div class="r27-ranking-controls" aria-label="점수 순위 범위">${buttons}<label>표시 인원<select id="rankingLimit27">${(d.limits||[10,30,50,100]).map(n=>`<option value="${n}" ${n===d.limit?'selected':''}>TOP ${n}</option>`).join('')}</select></label></div>${current.available?`<div class="r27-ranking-table-wrap"><table class="r27-ranking-table"><thead><tr><th>순위</th><th>학생</th><th>범위</th><th>${U.esc(d.scoreLabel||'점수')}</th></tr></thead><tbody>${rows||'<tr><td colspan="4">표시할 점수 기록이 없습니다.</td></tr>'}</tbody></table></div><p class="r27-ranking-note">${U.esc(d.tieRule||'')}</p>`:'<p>학급·학년 순위는 위에서 학년과 반을 선택하면 표시됩니다.</p>'}`}
function panelMarkup(panel){return panel?.key==='scoreRankings'?rankingMarkup(panel.data):panel?U.boardPanel(panel):'<p>교사 플랫폼에서 표시 항목을 켜 주세요.</p>'}

function render(){if(!data){root.innerHTML='<section class="panel"><h1>교실 학습 전광판</h1><p role="status">'+U.esc(error||'불러오는 중…')+'</p><p>잠시 후 자동으로 다시 조회합니다.</p></section>';return}const panel=data.panels[selected%Math.max(1,data.panels.length)];root.innerHTML=`<header class="r27-board-head"><div><p>HISTORY CLASSROOM · 1789–1799</p><h1>프랑스 혁명 학습 전광판</h1><p>${U.esc(data.schoolLabel||'')} ${U.esc(data.scopeLabel)} · ${U.date(data.generatedAt)} 갱신</p></div><button id="fullscreen27">전체 화면</button></header><section class="r27-board-controls"><form id="boardScope27"><label>학년<input name="grade" type="number" min="1" max="6" value="${filter.grade||''}"></label><label>반<input name="classNo" type="number" min="1" max="99" value="${filter.classNo||''}"></label><button ${pending?'disabled':''}>조회 범위 적용</button></form><button id="previous27">이전</button><button id="next27">다음</button><button id="rotation27" aria-pressed="${rotationPaused}">${rotationPaused?'전환 계속':'전환 멈춤'}</button><button id="logout27">로그아웃</button></section><section class="r27-board-panel" aria-live="polite"><h2>${U.esc(panel?.title||'표시 항목 없음')}</h2>${panelMarkup(panel)}</section><footer>${U.esc(error||data.notice)} · 서버 갱신 ${data.settings.refreshSeconds}초 / 화면 전환 ${rotationPaused?'멈춤':data.settings.rotateSeconds?data.settings.rotateSeconds+'초':'수동'}</footer>`;
 const full=document.querySelector('#fullscreen27');if(full)full.onclick=()=>{const p=document.fullscreenElement?document.exitFullscreen?.():document.documentElement.requestFullscreen?.();p?.catch?.(()=>{error='이 기기에서 전체 화면을 허용하지 않습니다.';render()})};
 document.querySelector('#previous27').onclick=()=>{selected=(selected-1+data.panels.length)%Math.max(1,data.panels.length);render()};document.querySelector('#next27').onclick=()=>{selected=(selected+1)%Math.max(1,data.panels.length);render()};document.querySelector('#rotation27').onclick=()=>{rotationPaused=!rotationPaused;render();armRotation()};document.querySelector('#logout27').onclick=async()=>{stop();data=null;try{await API.logout()}catch{error='연결을 확인해 주세요. 이 기기의 로그인 정보는 지웠습니다.'}finally{API.clear();login()}};
 document.querySelector('#boardScope27').onsubmit=e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));filter={schoolYear:filter.schoolYear,...(p.grade?{grade:+p.grade}:{}),...(p.grade&&p.classNo?{classNo:+p.classNo}:{})};selected=0;load()};
 document.querySelectorAll('[data-rank-scope]').forEach(button=>button.onclick=()=>{rankingScope=button.dataset.rankScope;render()});const limit=document.querySelector('#rankingLimit27');if(limit)limit.onchange=()=>{rankingLimit=+limit.value;load()};
}

async function load(){if(pending||document.hidden)return;pending=true;const owner=API.session?.token;clearTimeout(refreshTimer);try{const result=await API.request('teacher.board.read',{...filter,rankingLimit,...(API.session?.context3?{context3:{...API.session.context3,schoolYear:filter.schoolYear,grade:filter.grade||0,classNo:filter.classNo||0}}:{})});if(owner!==API.session?.token)return;data=result;error='';pending=false;selected=Math.min(selected,Math.max(0,data.panels.length-1));render();armRotation()}catch(e){pending=false;error=e.message;if(['SESSION_EXPIRED','AUTH_REQUIRED','SESSION_REVOKED','ACCESS_DENIED','FORBIDDEN'].includes(e.code)){API.clear();login();return}render()}finally{pending=false;if(['teacher','owner'].includes(API.session?.role))refreshTimer=setTimeout(load,Math.max(15,data?.settings.refreshSeconds||30)*1000)}}
addEventListener('history-session-changed',e=>{stop();data=null;selected=0;if(!e.detail?.authenticated)login()});addEventListener('pagehide',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else if(['teacher','owner'].includes(API.session?.role))load()});if(['teacher','owner'].includes(API.session?.role))load();else login();
})();
