(function(){'use strict';
 const cardKeys=['eventId','rarity','count','form','effectPolicy','effect','duplicate','unregistered'];
 function syncRewards(root=document){for(const box of root.querySelectorAll('.reward-fields25')){const select=box.querySelector('select[name$="kind"]');if(!select)continue;const prefix=select.name.slice(0,-4);for(const field of box.querySelectorAll('input,select')){const key=field.name.slice(prefix.length);if(key==='kind')continue;const visible=cardKeys.includes(key)?['card','both'].includes(select.value):['pack','both'].includes(select.value);field.disabled=!visible;field.closest('label').hidden=!visible;}const note=box.nextElementSibling;if(note?.matches('p.muted'))note.hidden=!['card','both'].includes(select.value);select.onchange=()=>syncRewards(root);}}
 function syncStudent(form){const select=form?.elements.studentId;if(!select)return;const student=info.students.find(s=>s.id===select.value);if(!student)return;const scoped=form.elements.scope?.value==='student';for(const key of ['schoolYear','grade','classNo','number','name']){const input=form.elements[key];if(!input)continue;if(scoped){input.value=student[key]??'';input.readOnly=true;}else input.readOnly=false;}let summary=form.querySelector('.rc-target-summary');if(!summary){summary=document.createElement('p');summary.className='rc-target-summary';form.querySelector('.formgrid')?.after(summary);}summary.textContent=scoped?`${student.schoolYear}학년도 · ${student.grade}학년 ${student.classNo}반 ${student.number}번 ${student.name} · 학생 ID ${student.id}`:'선택한 범위에 속한 학생에게 지급합니다.';}
 const targetBase=targetFields;
 targetFields=function(){return targetBase()+`<label>번호<input name="number" type="number" min="1" max="99"></label><label>이름<input name="name" readonly></label>`;};
 giveCards25=function(e){e.preventDefault();const form=e.target;syncStudent(form);const raw=formData(form),reward=readReward25(form,'gift_');if(!reward.card&&!reward.pack)return msg('지급할 보상을 선택하세요.');const target=Object.fromEntries(['scope','studentId','schoolYear','grade','classNo','unitId','reason'].filter(k=>raw[k]!==undefined).map(k=>[k,raw[k]]));const payload=reward.card?{...target,...reward.card,kind:reward.pack?'both':'card',unowned:reward.card.unregistered}:{...target,kind:'pack',packId:reward.pack.packId,count:reward.pack.count};if(reward.card&&reward.pack){payload.packId=reward.pack.packId;payload.packCount=reward.pack.count;}const student=info.students.find(s=>s.id===target.studentId);if(target.scope==='student'&&!student)return msg('지급할 학생을 먼저 선택하세요.');const who=target.scope==='student'?`${student.grade}학년 ${student.classNo}반 ${student.number}번 ${student.name}`:target.scope==='class'?`${target.grade}학년 ${target.classNo}반 전체`:target.scope==='grade'?`${target.grade}학년 전체`:`${target.schoolYear}학년도 선택 범위 전체`;const what=[reward.card?`카드 ${rarityNames[reward.card.rarity]||'무작위 등급'} ${reward.card.count}장`:null,reward.pack?`${packNames[reward.pack.packId]} ${reward.pack.count}개`:null].filter(Boolean).join(' + ');if(!confirm(`${who}\n${what}\n\n이 대상과 내용으로 지급하시겠습니까?`))return;task(async()=>{const out=await API.request('teacher.gift',payload);await refresh();msg(`${who}에게 ${what} 지급 완료. 저장 위치: ${[reward.card?'학생 카드 도감':null,reward.pack?'학생 카드팩 보관함':null].filter(Boolean).join(' + ')}.\n`+out.results.map(x=>x.studentId+': '+x.message).join('\n'));});};
 const renderBase=render;
 render=function(){renderBase();syncRewards();for(const form of document.querySelectorAll('form')){if(!form.elements.studentId)continue;syncStudent(form);form.elements.studentId.onchange=()=>syncStudent(form);if(form.elements.scope)form.elements.scope.onchange=()=>syncStudent(form);}const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);while(walker.nextNode())walker.currentNode.textContent=walker.currentNode.textContent.replaceAll('이로치','광휘');};
 document.head.appendChild(Object.assign(document.createElement('link'),{rel:'stylesheet',href:'rc-cinematic.css'}));document.head.appendChild(Object.assign(document.createElement('link'),{rel:'stylesheet',href:'rc-teacher.css'}));
 if(window.HISTORY_API_CONFIG?.rcLocalPreview&&new URLSearchParams(location.search).has('preview'))fetch('/__preview?role=teacher').then(r=>r.json()).then(async session=>{API.saveSession(session);await refresh();tab='cards';render();}).catch(e=>msg(e.message));else if(info)render();
 window.RCTeacher={syncRewards,syncStudent};
})();
