(function(){'use strict';
 const cardKeys=['eventId','rarity','count','form','effectPolicy','effect','duplicate','unregistered'];
 const targetKeys=['schoolYear','grade','classNo','number'];
 const numberValue=input=>{const value=Number(input?.value);return Number.isInteger(value)&&value>0?value:null;};
 function syncRewards(root=document){for(const box of root.querySelectorAll('.reward-fields25')){const select=box.querySelector('select[name$="kind"]');if(!select)continue;const prefix=select.name.slice(0,-4);for(const field of box.querySelectorAll('input,select')){const key=field.name.slice(prefix.length);if(key==='kind')continue;const visible=cardKeys.includes(key)?['card','both'].includes(select.value):['pack','both'].includes(select.value);field.disabled=!visible;field.closest('label').hidden=!visible;}const note=box.nextElementSibling;if(note?.matches('p.muted'))note.hidden=!['card','both'].includes(select.value);select.onchange=()=>syncRewards(root);}}
 function scopeDescription(form){const scope=form.elements.scope?.value,y=form.elements.schoolYear?.value,g=form.elements.grade?.value,c=form.elements.classNo?.value;return scope==='class'?`${y}학년도 · ${g}학년 ${c}반 전체`:scope==='grade'?`${y}학년도 · ${g}학년 전체`:scope==='year'?`${y}학년도 전체`:scope==='all'?'현재 학교·학년도 허용 범위 전체':'학생을 확인해 주세요.';}
 function syncStudent(form){if(!form?.elements.studentId)return;const scope=form.elements.scope?.value||'student',scoped=scope==='student';for(const key of ['number','name']){const input=form.elements[key];input?.closest('label')?.toggleAttribute('hidden',!scoped);if(input)input.disabled=!scoped;}const values=Object.fromEntries(targetKeys.map(key=>[key,numberValue(form.elements[key])]));const matches=scoped&&Object.values(values).every(Boolean)?info.students.filter(student=>targetKeys.every(key=>Number(student[key])===values[key])):[];const student=matches.length===1?matches[0]:null;form.elements.studentId.value=student?.id||'';if(form.elements.name)form.elements.name.value=student?.name||'';let summary=form.querySelector('.rc-target-summary');if(!summary){summary=document.createElement('p');summary.className='rc-target-summary';form.querySelector('.formgrid')?.after(summary);}summary.dataset.valid=String(!scoped||!!student);summary.textContent=!scoped?scopeDescription(form):student?`${student.schoolYear}학년도 · ${student.grade}학년 ${student.classNo}반 ${student.number}번 ${student.name} · 학생 확인 완료`:matches.length>1?'같은 학번의 학생이 둘 이상입니다. 명부 중복을 먼저 정리해 주세요.':'학년도·학년·반·번호를 모두 입력하면 이름을 자동 확인합니다.';const submit=form.querySelector('button[type="submit"],button:not([type])');if(submit)submit.disabled=scoped&&!student;}
 targetFields=function(){return`<label>대상 범위<select name="scope">${opts({student:'특정 학생',class:'반 전체',grade:'학년 전체',year:'학년도 전체',...(API.session?.role==='owner'?{all:'현재 학교·학년도 허용 범위 전체'}:{})},'student')}</select></label><label>학년도<input name="schoolYear" type="number" min="2000" max="2100" value="${year}" required></label><label>학년<input name="grade" type="number" min="1" max="6" value="${API.session?.context3?.grade||2}" required></label><label>반<input name="classNo" type="number" min="1" max="99" value="${API.session?.context3?.classNo||1}" required></label><label class="rc-target-field">번호<input name="number" type="number" min="1" max="99" inputmode="numeric" required></label><label class="rc-target-field">학생 이름<input name="name" autocomplete="off" readonly placeholder="번호 입력 후 자동 확인"></label><input name="studentId" type="hidden"><label>소단원<select name="unitId"><option value="fr-revolution">프랑스 혁명이 일어나다</option></select></label>`;};
 giveCards25=function(e){e.preventDefault();const form=e.target;syncStudent(form);const raw=formData(form),reward=readReward25(form,'gift_');if(!reward.card&&!reward.pack)return msg('지급할 보상을 선택하세요.');const target=Object.fromEntries(['scope','studentId','schoolYear','grade','classNo','unitId','reason'].filter(k=>raw[k]!==undefined).map(k=>[k,raw[k]]));const payload=reward.card?{...target,...reward.card,kind:reward.pack?'both':'card',unowned:reward.card.unregistered}:{...target,kind:'pack',packId:reward.pack.packId,count:reward.pack.count};if(reward.card&&reward.pack){payload.packId=reward.pack.packId;payload.packCount=reward.pack.count;}const student=info.students.find(s=>s.id===target.studentId);if(target.scope==='student'&&!student)return msg('학년도·학년·반·번호로 학생을 먼저 확인하세요.');const who=target.scope==='student'?`${student.grade}학년 ${student.classNo}반 ${student.number}번 ${student.name}`:target.scope==='class'?`${target.grade}학년 ${target.classNo}반 전체`:target.scope==='grade'?`${target.grade}학년 전체`:`${target.schoolYear}학년도 허용 범위 전체`;const what=[reward.card?`카드 ${rarityNames[reward.card.rarity]||'무작위 등급'} ${reward.card.count}장`:null,reward.pack?`${packNames[reward.pack.packId]} ${reward.pack.count}개`:null].filter(Boolean).join(' + ');if(!confirm(`${who}\n${what}\n\n이 대상을 마지막으로 확인하고 지급하시겠습니까?`))return;task(async()=>{const out=await API.request('teacher.gift',payload);await refresh();msg(`${who}에게 ${what} 지급 완료. 반영 위치: ${[reward.card?(reward.card.form==='shiny'?'학생 미개봉 교사 선물':'학생 카드 도감'):null,reward.pack?'학생 카드팩 보관함':null].filter(Boolean).join(' + ')}.\n`+(out.results||[]).map(x=>x.studentId+': '+x.message).join('\n'));});};
 const unlockGames={beginner:'초급',intermediate:'중급',advanced:'고급',connections:'혁명의 연결고리',revolutionmap:'혁명 지도·기억도전',matching:'짝맞추기',speedrun:'스피드런',baitrun:'미끼런'};
 function unlockPanel(){return `<section class="panel" id="rc-unlock-panel"><h2>특정 학생 게임 임시 해금</h2><p>선행 게임 완료 조건만 해제합니다. 완료 기록·XP·보상은 만들지 않으며, 수업 시간과 교사 잠금 설정은 유지합니다.</p><form id="rc-unlock-form" onsubmit="RCTeacher.createUnlock(event)"><div class="formgrid">${targetFields().replace(/<label>대상 범위[\s\S]*?<\/label>/,'<input type="hidden" name="scope" value="student">')}<label>해금 범위<select name="gameScope" onchange="document.getElementById('rc-unlock-games').hidden=this.value==='all'"><option value="all">현재 제공하는 모든 게임</option><option value="selected">선택한 게임</option></select></label><label>시작 시각 (한국시간, 공란은 즉시)<input type="datetime-local" name="startsAt"></label><label>기간<select name="duration">${opts({'60':'1시간','1440':'1일','10080':'7일','43200':'30일'},'60')}</select></label><label>사유<input name="reason" maxlength="300" placeholder="보충 학습 / 개별 테스트"></label></div><div id="rc-unlock-games" class="r27-checks" hidden>${Object.entries(unlockGames).map(([k,v])=>`<label><input type="checkbox" name="gameKey" value="${k}">${v}</label>`).join('')}</div><div class="actions"><button class="primary" type="submit">이 학생 임시 해금</button><button type="button" onclick="RCTeacher.readUnlocks()">선택 학생 권한·이력 조회</button></div></form><div id="rc-unlock-history" aria-live="polite"></div></section>`;}
 function unlockTarget(){const form=document.getElementById('rc-unlock-form');syncStudent(form);const p=formData(form);if(!p.studentId)throw new Error('학년도·학년·반·번호로 학생을 확인하세요.');return{form,p:{scope:'student',studentId:p.studentId,schoolYear:p.schoolYear,grade:p.grade,classNo:p.classNo,unitId:p.unitId},name:form.elements.name.value};}
 async function readUnlocks(){return task(async()=>{const {p}=unlockTarget(),out=await API.request('teacher.student.unlocks.read',p);showUnlocks(out);});}
 function showUnlocks(out){const host=document.getElementById('rc-unlock-history');if(!host)return;const current=document.getElementById('rc-unlock-form')?.elements.studentId.value;if(current!==out.student.id)return;host.innerHTML=`<h3>${E(out.student.name)} · 임시 해금 이력</h3>`+(out.items.map(r=>`<article class="panel"><b>${E(r.gameKeys.map(k=>unlockGames[k]||k).join(', '))}</b><p>${E(new Date(r.startsAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))} ~ ${E(new Date(r.expiresAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))}</p><p>${E({active:'사용 가능',scheduled:'시작 대기',expired:'자동 만료',revoked:'취소됨'}[r.status])} · ${E(r.reason)}</p>${['active','scheduled'].includes(r.status)?`<button type="button" onclick="RCTeacher.revokeUnlock('${r.id}','${out.student.id}')">해금 취소</button>`:''}</article>`).join('')||'<p>임시 해금 이력이 없습니다.</p>');}
 async function createUnlock(e){e.preventDefault();return task(async()=>{const {form,p,name}=unlockTarget(),start=form.elements.startsAt.value?new Date(form.elements.startsAt.value+':00+09:00'):new Date(),gameKeys=form.elements.gameScope.value==='all'?'all':[...form.querySelectorAll('[name="gameKey"]:checked')].map(n=>n.value);if(Array.isArray(gameKeys)&&!gameKeys.length)throw new Error('게임을 한 개 이상 선택하세요.');if(!confirm(`${p.grade}학년 ${p.classNo}반 ${form.elements.number.value}번 ${name}\n${gameKeys==='all'?'현재 모든 게임':gameKeys.map(k=>unlockGames[k]).join(', ')}을 임시 해금할까요?\n실제 완료 기록은 변경되지 않습니다.`))return;await API.request('teacher.student.unlocks.create',{...p,gameKeys,startsAt:form.elements.startsAt.value?start.toISOString():'',expiresAt:new Date(start.getTime()+Number(form.elements.duration.value)*60000).toISOString(),reason:form.elements.reason.value});showUnlocks(await API.request('teacher.student.unlocks.read',p));msg('임시 해금했습니다. 종료 시각에 자동 만료됩니다.');});}
 async function revokeUnlock(unlockId,studentId){return task(async()=>{const {p,name}=unlockTarget();if(p.studentId!==studentId)throw new Error('학생을 다시 확인하세요.');if(!confirm(`${name} 학생의 이 임시 해금을 취소할까요?`))return;await API.request('teacher.student.unlocks.revoke',{...p,unlockId});showUnlocks(await API.request('teacher.student.unlocks.read',p));});}
 const renderBeforeUnlock=render;
 render=function(){renderBeforeUnlock();if(info&&['cards','learning26'].includes(tab))el.querySelector('main')?.insertAdjacentHTML('beforeend',unlockPanel());};
 const renderBase=render;
 render=function(){renderBase();syncRewards();for(const form of document.querySelectorAll('form')){if(!form.elements.studentId)continue;syncStudent(form);for(const key of ['scope',...targetKeys]){const input=form.elements[key];if(!input)continue;input.addEventListener(key==='scope'?'change':'input',()=>syncStudent(form));}}for(const row of document.querySelectorAll('.student-row-code'))if(!row.querySelector('.copy-code-ready')){const button=document.createElement('button');button.type='button';button.className='copy-code-ready';button.textContent='새 코드 복사';button.onclick=async()=>{const code=row.querySelector('.credential')?.textContent||'';await navigator.clipboard.writeText(code);msg('새 접속 코드를 복사했습니다. 이 화면을 닫으면 다시 조회할 수 없습니다.');};row.append(button)}const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);while(walker.nextNode())walker.currentNode.textContent=walker.currentNode.textContent.replaceAll('이로치','광휘').replaceAll('기존 확률·천장 설정','카드팩 확률·천장');};
 document.head.appendChild(Object.assign(document.createElement('link'),{rel:'stylesheet',href:'rc-cinematic.css?v=42-rc-cssfix-20260922'}));document.head.appendChild(Object.assign(document.createElement('link'),{rel:'stylesheet',href:'rc-teacher.css?v=42-rc-cssfix-20260922'}));
 if(window.HISTORY_API_CONFIG?.rcLocalPreview&&new URLSearchParams(location.search).has('preview'))fetch('/__preview?role=teacher').then(r=>r.json()).then(async session=>{API.saveSession(session);await refresh();tab='cards';render();}).catch(e=>msg(e.message));else if(info)render();
 window.RCTeacher={syncRewards,syncStudent,createUnlock,readUnlocks,revokeUnlock};
})();
