/* Reveal-only UI. One server batch per opening; every subsequent card click is local. */
let opening28=null,openingOwner28='',openingList28=null,revealBusy28=false,revealUnlock28=null,openingMode28='',openingZoom28=false,singleOpened28=0;
const packByIdBeforeGift28=packByIdV36;packByIdV36=function(id){return id==='gift'?{id:'gift',name:'교사 직접 지급 카드',short:'교사 선물',crest:'✦',note:'교사가 지급한 서버 확정 결과'}:packByIdBeforeGift28(id)};
const revealModes28={single:'1장씩 까기',all:'모두 까기'};
const ownerKey28=()=>state42?state42.profile.schoolYear+':'+state42.profile.id:'';
const revealMode28=()=>state42?.learning26?.preferences.packReveal||'manual';
function cursorKey28(id){return 'history-reveal28:'+ownerKey28()+':'+id;}
function storeCursor28(){if(!opening28)return;try{sessionStorage.setItem(cursorKey28(opening28.id),String(packReward?.revealed||0))}catch{}}
function clearOpening28(){clearTimeout(packAutoTimerV38);clearTimeout(revealUnlock28);packAutoV38=false;opening28=null;packReward=null;openPlan42=null;revealBusy28=false;openingMode28='';openingZoom28=false;singleOpened28=0;}
function resetStudent28(){const prefix='history-reveal28:'+ownerKey28()+':';try{for(let i=sessionStorage.length-1;i>=0;i--){const k=sessionStorage.key(i);if(k?.startsWith(prefix))sessionStorage.removeItem(k)}}catch{}clearOpening28();openingList28=null;openingOwner28='';attempts42={};rank42=portal42=null;records27=null;recordsOwner27='';recordRequest27++;cardInspect=null;replay25=null;stage2Dialog=null;fusionSlotsV34=[];boards26={};selected26=null;autoStamp26={};speed=bait=matchGame=face=null;clearTimeout(mapTimer26);clearTimeout(autoTimer26);clearTimeout(draft42);clearTimeout(matchPreviewTimer42);matchPreviewEpoch42++;P=fresh();}
function localOpeningSummary28(row){if(!state42?.packOpenings28)return;const s=state42.packOpenings28,wasPending=s.pending.some(x=>x.id===row.id);openingList28=null;for(const list of [s.pending,s.recent]){const x=list.find(x=>x.id===row.id);if(x)Object.assign(x,row)}if(row.seenAt){s.pending=s.pending.filter(x=>x.id!==row.id);s.recent=[row,...s.recent.filter(x=>x.id!==row.id)].slice(0,10);s.pendingCount=Math.max(s.pending.length,s.pendingCount-(wasPending?1:0))}}
async function ackOpening28(seen=false){if(!opening28)return;const id=opening28.id,owner=ownerKey28(),revealed=packReward.revealed;storeCursor28();try{const out=await api42.request('cards.openings.ack',{openingId:id,revealed,seen});if(owner===ownerKey28()){localOpeningSummary28(out.opening);if(opening28?.id===id)Object.assign(opening28,out.opening)}}catch(e){if(owner===ownerKey28())toast42('확인 위치를 저장하지 못했습니다. 획득한 카드는 보존되어 있으며 보관함에서 다시 확인할 수 있습니다.')}}
function attachOpening28(row,mode='all'){api42.resolveRequest?.(row.requestId);opening28=clone42(row);openingOwner28=ownerKey28();openingMode28=mode==='single'?'single':'all';openingZoom28=false;openPlan42=null;let saved=0;try{saved=Number(sessionStorage.getItem(cursorKey28(row.id)))||0}catch{}const n=openingMode28==='single'?1:Math.min(row.cards.length,Math.max(row.revealed||0,saved));packReward={packType:row.packId,cards:row.cards.map(cardFrom42),cursor:Math.max(0,n-1),revealed:n,phase:n?'shown':'covered',source:'cardpacks28'};if(openingMode28==='single')singleOpened28++;render42();}
openStoredPacksV38=(packId,mode='single')=>{if(busy42||opening28)return;const available=loadPackInventoryV38().counts[packId]||0;if(available<1)return;clearOpening28();openPlan42={packId,total:available,mode:mode==='all'?'all':'single',selected:true};openingOwner28=ownerKey28();render42()};
async function beginOpening28(mode){if(!openPlan42||opening28)return;const plan={...openPlan42},owner=ownerKey28(),chosen=mode||plan.mode||'single',count=chosen==='all'?plan.total:1;return run42(async()=>{const out=await api42.request('cards.openPack',{packId:plan.packId,count});if(owner!==ownerKey28())return;applyState42(out.student);attachOpening28(out.opening,chosen)})}
function revealNext28(){if(busy42||revealBusy28||!opening28||!packReward||packReward.phase==='done'||openingMode28==='single')return;if(packReward.revealed>=packReward.cards.length)return showAllOpening28();revealBusy28=true;openingZoom28=false;packReward.cursor=packReward.revealed;packReward.revealed++;packReward.phase='shown';storeCursor28();render42();clearTimeout(revealUnlock28);revealUnlock28=setTimeout(()=>{revealBusy28=false},320);}
function showAllOpening28(){if(!opening28)return;clearTimeout(packAutoTimerV38);packAutoV38=false;packReward.revealed=packReward.cards.length;packReward.cursor=packReward.cards.length;packReward.phase='done';storeCursor28();render42();/* acknowledgement only; never grant again */void ackOpening28(true);}
revealPack=()=>openPlan42?beginOpening28():revealNext28();
advancePackV38=()=>opening28?advanceOpening28():advance42Base();
revealAllPackV39=()=>openPlan42?beginOpening28('all'):undefined;
autoOpenPackV39=()=>{};
schedulePackAutoV38=()=>{};
function toggleOpeningZoom28(){if(!opening28||!packReward?.revealed)return;openingZoom28=!openingZoom28;render42()}
async function advanceOpening28(){if(busy42||revealBusy28||!opening28)return;if(openingMode28!=='single')return revealNext28();const packId=opening28.packId,remaining=loadPackInventoryV38().counts[packId]||0;await ackOpening28(true);opening28=null;packReward=null;openingZoom28=false;if(remaining<1){openPlan42=null;openingMode28='';render42();return}openPlan42={packId,total:Math.min(100,remaining),mode:'single',selected:true};render42();return beginOpening28('single')}
const oldClose28=closePackV38;
closePackV38=()=>{if(busy42)return;if(opening28)void ackOpening28(openingMode28==='single'||packReward.phase==='done');clearOpening28();oldClose28();};
async function resumeOpening28(id,all=false){return run42(async()=>{const owner=ownerKey28(),out=await api42.request('cards.openings.read',{openingId:id});if(owner===ownerKey28())attachOpening28(out.opening,'all')})}
async function openTeacherGift28(id){if(busy42||opening28)return;return run42(async()=>{const owner=ownerKey28(),out=await api42.request('cards.teacherGifts.open',{giftOpeningId:id});if(owner!==ownerKey28())return;applyState42(out.student);attachOpening28(out.opening,'all');});}
function teacherGifts28(){const gifts=state42?.teacherGifts||[];return gifts.length?`<section class="opening-history28"><h3>미개봉 교사 선물 · ${gifts.reduce((n,g)=>n+g.count,0)}장</h3><p>선생님이 보내신 확정 카드입니다. 열 때 재추첨하거나 카드팩을 차감하지 않습니다.</p>${gifts.map(g=>`<article class="opening-row28"><span>${escape41(packByIdV36(g.packId).name)} · 광휘 선물 ${g.count}장</span><button class="btn" onclick="openTeacherGift28('${g.id}')">선물 열기</button></article>`).join('')}</section>`:'';}
function navigateOpening28(where){closePackV38();if(busy42)return;collectionModeV34=where;go('collection');}
function packCard28(x){return`<span class="opening-card-wrap28">${cardMarkup25(x.event.id,x.rar.id,x.count,'reveal',x.effect).replace(/tabindex="0"/g,'tabindex="-1"')}${x.isNew?'<b class="opening-new28">NEW</b>':''}</span>`;}
function packCaption28(x){return`<div class="reveal-caption28 ${x.rar.id}"><strong class="rarity-label42">${escape41(x.rar.name)}</strong>${x.isNew?'<b>최초 획득</b>':`<b>중복 · 현재 보유 ${x.count}장</b>`}<strong class="revealed-title42">${escape41(x.event.title)}</strong>${x.shiny?`<b class="shiny-banner25">광휘 · ${escape41(effectName25(x.effect))}</b>`:''}</div>`}
function openingSummary28(cards){const rarity=Object.fromEntries(HistoryCards.TIERS.map(r=>[r.id,0])),effects={},newGlow=new Set();let normal=0,shiny=0,fresh=0;for(const card of cards){rarity[card.rar.id]=(rarity[card.rar.id]||0)+1;if(card.shiny){shiny++;effects[card.effect]=(effects[card.effect]||0)+1;if(card.isNew)newGlow.add(`${card.event.id}:${card.rar.id}:${card.effect}`)}else normal++;if(card.isNew)fresh++}return{rarity,effects,normal,shiny,fresh,duplicates:cards.length-fresh,newGlow:newGlow.size}}
function openingSummaryMarkup28(cards){const s=openingSummary28(cards);return`<section class="opening-summary28" aria-label="개봉 결과 요약"><h3>획득 요약</h3><div class="opening-summary-grid28">${HistoryCards.TIERS.map(r=>`<span><b>${escape41(r.name)}</b>${s.rarity[r.id]||0}</span>`).join('')}<span><b>일반</b>${s.normal}</span><span><b>광휘</b>${s.shiny}</span><span><b>새 카드</b>${s.fresh}</span><span><b>중복 카드</b>${s.duplicates}</span><span><b>새 광휘</b>${s.newGlow}</span></div>${Object.keys(s.effects).length?`<p>광휘 종류 · ${Object.entries(s.effects).map(([effect,count])=>`${escape41(effectName25(effect))} ${count}`).join(' · ')}</p>`:'<p>이번 결과에는 광휘 카드가 없습니다.</p>'}</section>`}
function rewardCards28(result){return(result?.cards||[]).flatMap(card=>Array.isArray(card.variants)?card.variants:card&&card.eventId!==undefined?[card]:[])}
function rewardSummary28(result){const cards=rewardCards28(result),fresh=cards.filter(x=>x.isNew),newGlow=new Set(fresh.filter(x=>x.shiny||x.effect&&x.effect!=='normal').map(x=>`${x.eventId}:${x.rarity}:${x.effect}`));return{cards,newCards:fresh.length,duplicates:cards.length-fresh.length,newGlow:newGlow.size}}
function rewardSummaryText28(result){const s=rewardSummary28(result);return s.cards.length?`새 카드 ${s.newCards}장 · 중복 카드 ${s.duplicates}장 · 새 광휘 ${s.newGlow}종`:''}
const rewardNoticeBase28=rewardNotice42;rewardNotice42=function(kind,result){const summary=rewardSummaryText28(result);return[rewardNoticeBase28(kind,result),summary].filter(Boolean).join(' · ')};
const completionNoticeBase28=completionNotice2;completionNotice2=function(a){const r=a?.completionReward||a?.state?.rewardResult,summary=rewardSummaryText28(r),html=completionNoticeBase28(a);return summary?html.replace('<div class="bonus-actions">',`<p class="opening-summary-inline28"><strong>${escape41(summary)}</strong><br>NEW 판정은 서버가 확정했으며 다시 열어도 바뀌지 않습니다.</p><div class="bonus-actions">`):html};
const celebrationBase28=celebration25;celebration25=function(x){const summary=rewardSummaryText28(x?.result),html=celebrationBase28(x);return summary?html.replace('<div class="actions25">',`<p class="opening-summary-inline28"><strong>${escape41(summary)}</strong></p><div class="actions25">`):html};
const oldReward28=rewardModal;
rewardModal=function(){if(!opening28&&!openPlan42)return oldReward28();const waiting=!!openPlan42,p=packByIdV36(waiting?openPlan42.packId:opening28.packId),done=!waiting&&packReward.phase==='done',n=waiting?0:packReward.revealed,total=waiting?openPlan42.total:packReward.cards.length,x=!waiting&&n?packReward.cards[Math.min(n-1,total-1)]:null;
const selectedMode=waiting?(openPlan42.mode||'single'):openingMode28,remaining=waiting?(loadPackInventoryV38().counts[openPlan42.packId]||0):(loadPackInventoryV38().counts[opening28.packId]||0),progress=selectedMode==='single'&&!waiting?`이번에 ${singleOpened28}장 개봉 · 팩 ${remaining}개 남음`:`${n} / ${total}${done?' · 전체 결과':''}`,zoom=x&&openingZoom28?`<div class="opening-zoom28" onclick="toggleOpeningZoom28()"><button type="button" onclick="event.stopPropagation();toggleOpeningZoom28()" aria-label="확대 닫기">${packCard28(x)}</button></div>`:'';
return`<div class="rewardmodal v41-reward reveal-modal28" role="dialog" aria-modal="true" aria-labelledby="opening-title28"><section class="packbox v41-packbox reveal-box28 ${done?'opening-result28':''}"><h2 id="opening-title28">${done?'개봉 완료 · 총 '+total+'장':escape41(p.name)}</h2><p class="reveal-progress28" role="status">${waiting?revealModes28[selectedMode]:progress}</p>${waiting?`<button type="button" class="sealed-pack28 sealed-pack" onclick="beginOpening28('${selectedMode}')" aria-label="${escape41(p.name)} ${revealModes28[selectedMode]}"><img src="${packAsset41(p.id)}" alt="${escape41(p.name)}"><span>${revealModes28[selectedMode]}</span></button><p>${selectedMode==='single'?'버튼 또는 Enter를 누를 때마다 팩 1개와 카드 1장만 처리됩니다. 닫으면 남은 팩은 그대로 유지됩니다.':`보유 팩 ${total}개를 서버에서 한 번에 확정한 뒤, 결과를 한 장씩 확인합니다.`}</p>`:done?`<div class="reveal-grid28">${packReward.cards.map((c,i)=>`<article><span>${i+1} / ${total}</span><div class="reveal-static28">${packCard28(c)}</div>${packCaption28(c)}</article>`).join('')}</div>${openingSummaryMarkup28(packReward.cards)}`:`<div class="reveal-stage28">${x?`<button type="button" class="reveal-card28 card-spotlight42 ${x.rar.id}" onclick="toggleOpeningZoom28()" aria-label="카드 확대">${packCard28(x)}</button>${packCaption28(x)}`:'<div class="reveal-card28"><span class="card-back28">✦<b>개봉을 기다리는 카드</b></span></div><p>다음 카드 개봉 버튼 또는 Enter를 눌러 주세요.</p>'}</div>`}${zoom}<div class="reveal-actions28">${waiting?`<button class="btn" onclick="beginOpening28('${selectedMode}')">${revealModes28[selectedMode]}</button>`:!done&&selectedMode==='all'?`<button class="btn" onclick="advanceOpening28()">${n<total?'다음 카드 개봉':'개봉 결과 보기'}</button>`:!done&&selectedMode==='single'&&remaining?'<button class="btn" onclick="advanceOpening28()">다음 1장 까기</button>':''}<button class="btn alt" onclick="navigateOpening28('packs')">보관함으로</button>${!waiting?'<button class="btn alt" onclick="navigateOpening28(\'book\')">카드 도감에서 확인</button>':''}<button class="btn alt" onclick="closePackV38()">닫기</button></div>${!waiting?'<p>카드와 NEW 여부는 서버가 확정하여 저장합니다. 카드를 누르면 확대만 되며 다음 카드로 넘어가지 않습니다.</p>':''}</section></div>`;};
function vaultContent28(){const counts=loadPackInventoryV38().counts;return `<h2>카드팩 보관함</h2><div class="packvault38">${PACKS_V36.map(p=>{const n=counts[p.id]||0;return `<article class="vaultitem38">${packBackV36(p,true)}<h3>${escape41(p.name)}</h3><p>보관 ${n}개</p><div class="vaultactions38"><button class="btn" onclick="openStoredPacksV38('${p.id}','single')" ${n?'':'disabled'}>1장씩 까기</button><button class="btn alt" onclick="openStoredPacksV38('${p.id}','all')" ${n?'':'disabled'}>모두 까기${n?` · ${n}개`:''}</button></div></article>`}).join('')}</div>`}
packVaultV38=function(){const s=state42?.packOpenings28||{pending:[],recent:[],pendingCount:0},items=openingList28?.items||s.pending;return`<section class="opening-history28"><h3>${s.pendingCount?'확인하지 않은 카드 개봉 결과가 있습니다':'카드 개봉 결과'}</h3>${items.map(r=>openingRow28(r)).join('')}${s.pendingCount>20?'<button class="btn alt" onclick="loadOpenings28()">미확인 결과 목록 새로 보기</button>':''}${openingList28?.nextOffset!==null&&openingList28?.nextOffset!==undefined?`<button class="btn alt" onclick="loadOpenings28(${openingList28.nextOffset})">다음 결과 목록</button>`:''}${s.recent.length?'<details><summary>최근 확인한 개봉 결과</summary>'+s.recent.map(openingRow28).join('')+'</details>':''}</section>`+vaultContent28();};
function openingRow28(r){return`<article class="opening-row28"><span>${r.source==='teacherGift'?'교사 선물 · ':''}${escape41(packByIdV36(r.packId).name)} ${r.count}장 · ${r.revealed}/${r.count} 확인</span><button class="btn" onclick="resumeOpening28('${r.id}')">이어서 보기</button></article>`}
const packVaultBeforeGifts28=packVaultV38;packVaultV38=()=>teacherGifts28()+packVaultBeforeGifts28();
async function loadOpenings28(offset=0){return run42(async()=>{const owner=ownerKey28(),out=await api42.request('cards.openings.list',{offset});if(owner===ownerKey28()){openingList28=out;render42()}})}
const oldPreference28=preferencePage26;
preferencePage26=()=>oldPreference28();
const oldApply28=applyState42;
applyState42=function(s){if(s&&state42&&s.profile.id!==state42.profile.id)resetStudent28();oldApply28(s);};
const oldRender28=render42;
render42=function(){if(openingOwner28&&openingOwner28!==ownerKey28())resetStudent28();oldRender28();HistoryUI28.enhance();};
const oldProfile28=profileScreen;profileScreen=function(){resetStudent28();oldProfile28();HistoryUI28.enhance();};
logout42=async function(){resetStudent28();state42=null;profile=null;try{await api42.logout()}catch{toast42('연결을 확인해 주세요. 이 기기의 로그인 정보는 지웠습니다.')}finally{api42.clear();profileScreen()}};
addEventListener('history-session-changed',e=>{resetStudent28();state42=null;profile=null;if(!e.detail?.authenticated)profileScreen()});
document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(packAutoTimerV38);storeCursor28()}else schedulePackAutoV38()});
addEventListener('pagehide',storeCursor28);
addEventListener('keydown',e=>{if(e.key!=='Enter'||(!opening28&&!openPlan42)||['INPUT','TEXTAREA','SELECT','BUTTON'].includes(e.target?.tagName))return;e.preventDefault();e.stopImmediatePropagation();if(e.repeat||busy42||revealBusy28)return;if(openPlan42)beginOpening28(openPlan42.mode);else if(packReward?.phase!=='done')advanceOpening28();},true);
render=renderV28=renderV29=renderV30=renderV31=renderV32=renderV33=renderV34=renderV35=renderV36=renderV37=renderV38=renderV39=renderV40=renderV41=render42;
