-- Isolated normal-version RC. Does not alter history_rc or its live API.
create schema history_v5;
revoke all on schema history_v5 from public, anon, authenticated;
create role history_v5_worker nologin;
grant usage on schema history_v5 to history_v5_worker;
create table history_v5.environment(id boolean primary key default true check(id), source_commit text not null, created_at timestamptz not null default now());
insert into history_v5.environment(source_commit) values ('8e1e26d973000a30e2d09212667c800347f273a7');
create table history_v5.catalog(logical_name text primary key, physical_name text unique not null, shared boolean not null);
create table history_v5.settings_checkpoint(logical_name text not null, id text not null, data jsonb not null, primary key(logical_name,id));
create table history_v5.login_receipts(actor text not null, request_id text not null, body_hash text not null, envelope jsonb not null, created_at timestamptz not null default now(), primary key(actor,request_id));
create table history_v5.backup_objects(id text primary key, envelope jsonb not null);
create table history_v5.restore_copies(id text primary key, tables jsonb not null, created_at timestamptz not null default now());

create table history_v5.gas_schools3(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_schools3(owner_id);
insert into history_v5.catalog values ('schools3','gas_schools3',true);
insert into history_v5.gas_schools3(id,data) select id,data from history_rc.gas_schools3 where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'schools3',id,data from history_v5.gas_schools3;
create table history_v5.gas_studentscopes3(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_studentscopes3(owner_id);
insert into history_v5.catalog values ('studentScopes3','gas_studentscopes3',false);
insert into history_v5.gas_studentscopes3(id,data) select id,data from history_rc.gas_studentscopes3 where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'studentScopes3',id,data from history_v5.gas_studentscopes3;
create table history_v5.gas_sessionscopes3(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_sessionscopes3(owner_id);
insert into history_v5.catalog values ('sessionScopes3','gas_sessionscopes3',false);
create table history_v5.gas_sessionrevocations3(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'userId') stored);
create index on history_v5.gas_sessionrevocations3(owner_id);
insert into history_v5.catalog values ('sessionRevocations3','gas_sessionrevocations3',false);
create table history_v5.gas_scopedsettings3(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_scopedsettings3(owner_id);
insert into history_v5.catalog values ('scopedSettings3','gas_scopedsettings3',true);
insert into history_v5.gas_scopedsettings3(id,data) select id,data from history_rc.gas_scopedsettings3 where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'scopedSettings3',id,data from history_v5.gas_scopedsettings3;
create table history_v5.gas_objectscopes3(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'actorId') stored);
create index on history_v5.gas_objectscopes3(owner_id);
insert into history_v5.catalog values ('objectScopes3','gas_objectscopes3',true);
insert into history_v5.gas_objectscopes3(id,data) select id,data from history_rc.gas_objectscopes3 where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'objectScopes3',id,data from history_v5.gas_objectscopes3;
create table history_v5.gas_ownerrecovery3(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_ownerrecovery3(owner_id);
insert into history_v5.catalog values ('ownerRecovery3','gas_ownerrecovery3',true);
insert into history_v5.gas_ownerrecovery3(id,data) select id,data from history_rc.gas_ownerrecovery3 where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'ownerRecovery3',id,data from history_v5.gas_ownerrecovery3;
create table history_v5.gas_packopenings28(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_packopenings28(owner_id);
insert into history_v5.catalog values ('packOpenings28','gas_packopenings28',false);
create table history_v5.gas_reportsettings27(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_reportsettings27(owner_id);
insert into history_v5.catalog values ('reportSettings27','gas_reportsettings27',true);
insert into history_v5.gas_reportsettings27(id,data) select id,data from history_rc.gas_reportsettings27 where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'reportSettings27',id,data from history_v5.gas_reportsettings27;
create table history_v5.gas_questionevents27(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_questionevents27(owner_id);
insert into history_v5.catalog values ('questionEvents27','gas_questionevents27',false);
create table history_v5.gas_attemptevents27(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_attemptevents27(owner_id);
insert into history_v5.catalog values ('attemptEvents27','gas_attemptevents27',false);
create table history_v5.gas_loginevents27(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_loginevents27(owner_id);
insert into history_v5.catalog values ('loginEvents27','gas_loginevents27',false);
create table history_v5.gas_grantevents27(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_grantevents27(owner_id);
insert into history_v5.catalog values ('grantEvents27','gas_grantevents27',false);
create table history_v5.gas_boardsnapshots27(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_boardsnapshots27(owner_id);
insert into history_v5.catalog values ('boardSnapshots27','gas_boardsnapshots27',false);
create table history_v5.gas_learningsettings26(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_learningsettings26(owner_id);
insert into history_v5.catalog values ('learningSettings26','gas_learningsettings26',true);
insert into history_v5.gas_learningsettings26(id,data) select id,data from history_rc.gas_learningsettings26 where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'learningSettings26',id,data from history_v5.gas_learningsettings26;
create table history_v5.gas_learning26(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_learning26(owner_id);
insert into history_v5.catalog values ('learning26','gas_learning26',false);
create table history_v5.gas_xp26(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_xp26(owner_id);
insert into history_v5.catalog values ('xp26','gas_xp26',false);
create table history_v5.gas_xpclaims26(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_xpclaims26(owner_id);
insert into history_v5.catalog values ('xpClaims26','gas_xpclaims26',false);
create table history_v5.gas_levelclaims26(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_levelclaims26(owner_id);
insert into history_v5.catalog values ('levelClaims26','gas_levelclaims26',false);
create table history_v5.gas_studyclaims26(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_studyclaims26(owner_id);
insert into history_v5.catalog values ('studyClaims26','gas_studyclaims26',false);
create table history_v5.gas_missionassignments26(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_missionassignments26(owner_id);
insert into history_v5.catalog values ('missionAssignments26','gas_missionassignments26',false);
create table history_v5.gas_preferences26(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_preferences26(owner_id);
insert into history_v5.catalog values ('preferences26','gas_preferences26',false);
create table history_v5.gas_system(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->'value'->>'studentId') stored);
create index on history_v5.gas_system(owner_id);
insert into history_v5.catalog values ('system','gas_system',false);
insert into history_v5.gas_system(id,data) select id,data from history_rc.gas_system where namespace='rc-fr42-20260920' and coalesce(data->>'key','') not like 'device-login:%';
insert into history_v5.settings_checkpoint select 'system',id,data from history_v5.gas_system;
create table history_v5.gas_games(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_games(owner_id);
insert into history_v5.catalog values ('games','gas_games',true);
insert into history_v5.gas_games(id,data) select id,data from history_rc.gas_games where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'games',id,data from history_v5.gas_games;
create table history_v5.gas_visibility(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_visibility(owner_id);
insert into history_v5.catalog values ('visibility','gas_visibility',true);
insert into history_v5.gas_visibility(id,data) select id,data from history_rc.gas_visibility where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'visibility',id,data from history_v5.gas_visibility;
create table history_v5.gas_access(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_access(owner_id);
insert into history_v5.catalog values ('access','gas_access',true);
insert into history_v5.gas_access(id,data) select id,data from history_rc.gas_access where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'access',id,data from history_v5.gas_access;
create table history_v5.gas_rewards(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_rewards(owner_id);
insert into history_v5.catalog values ('rewards','gas_rewards',true);
insert into history_v5.gas_rewards(id,data) select id,data from history_rc.gas_rewards where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'rewards',id,data from history_v5.gas_rewards;
create table history_v5.gas_completionrules(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_completionrules(owner_id);
insert into history_v5.catalog values ('completionRules','gas_completionrules',true);
insert into history_v5.gas_completionrules(id,data) select id,data from history_rc.gas_completionrules where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'completionRules',id,data from history_v5.gas_completionrules;
create table history_v5.gas_completionclaims(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_completionclaims(owner_id);
insert into history_v5.catalog values ('completionClaims','gas_completionclaims',false);
create table history_v5.gas_collectionsettings(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_collectionsettings(owner_id);
insert into history_v5.catalog values ('collectionSettings','gas_collectionsettings',true);
insert into history_v5.gas_collectionsettings(id,data) select id,data from history_rc.gas_collectionsettings where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'collectionSettings',id,data from history_v5.gas_collectionsettings;
create table history_v5.gas_cardvariants(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_cardvariants(owner_id);
insert into history_v5.catalog values ('cardVariants','gas_cardvariants',false);
create table history_v5.gas_collectionprogress(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_collectionprogress(owner_id);
insert into history_v5.catalog values ('collectionProgress','gas_collectionprogress',false);
create table history_v5.gas_collectionclaims(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_collectionclaims(owner_id);
insert into history_v5.catalog values ('collectionClaims','gas_collectionclaims',false);
create table history_v5.gas_shinywallet(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_shinywallet(owner_id);
insert into history_v5.catalog values ('shinyWallet','gas_shinywallet',false);
create table history_v5.gas_activities(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_activities(owner_id);
insert into history_v5.catalog values ('activities','gas_activities',false);
create table history_v5.gas_missionprograms(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_missionprograms(owner_id);
insert into history_v5.catalog values ('missionPrograms','gas_missionprograms',true);
insert into history_v5.gas_missionprograms(id,data) select id,data from history_rc.gas_missionprograms where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'missionPrograms',id,data from history_v5.gas_missionprograms;
create table history_v5.gas_missionruns(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'actorId') stored);
create index on history_v5.gas_missionruns(owner_id);
insert into history_v5.catalog values ('missionRuns','gas_missionruns',true);
insert into history_v5.gas_missionruns(id,data) select id,data from history_rc.gas_missionruns where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'missionRuns',id,data from history_v5.gas_missionruns;
create table history_v5.gas_missionclaims(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_missionclaims(owner_id);
insert into history_v5.catalog values ('missionClaims','gas_missionclaims',false);
create table history_v5.gas_attendancerules(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_attendancerules(owner_id);
insert into history_v5.catalog values ('attendanceRules','gas_attendancerules',true);
insert into history_v5.gas_attendancerules(id,data) select id,data from history_rc.gas_attendancerules where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'attendanceRules',id,data from history_v5.gas_attendancerules;
create table history_v5.gas_securityevents(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_securityevents(owner_id);
insert into history_v5.catalog values ('securityEvents','gas_securityevents',false);
create table history_v5.gas_teacherpolicies(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_teacherpolicies(owner_id);
insert into history_v5.catalog values ('teacherPolicies','gas_teacherpolicies',true);
insert into history_v5.gas_teacherpolicies(id,data) select id,data from history_rc.gas_teacherpolicies where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'teacherPolicies',id,data from history_v5.gas_teacherpolicies;
create table history_v5.gas_teachers(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_teachers(owner_id);
insert into history_v5.catalog values ('teachers','gas_teachers',true);
insert into history_v5.gas_teachers(id,data) select id,data from history_rc.gas_teachers where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'teachers',id,data from history_v5.gas_teachers;
create table history_v5.gas_students(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'id') stored);
create index on history_v5.gas_students(owner_id);
insert into history_v5.catalog values ('students','gas_students',false);
insert into history_v5.gas_students(id,data) select id,data from history_rc.gas_students where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'students',id,data from history_v5.gas_students;
create table history_v5.gas_sessions(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'userId') stored);
create index on history_v5.gas_sessions(owner_id);
insert into history_v5.catalog values ('sessions','gas_sessions',false);
create table history_v5.gas_progress(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_progress(owner_id);
insert into history_v5.catalog values ('progress','gas_progress',false);
create table history_v5.gas_attempts(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_attempts(owner_id);
insert into history_v5.catalog values ('attempts','gas_attempts',false);
create table history_v5.gas_records(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_records(owner_id);
insert into history_v5.catalog values ('records','gas_records',false);
create table history_v5.gas_speed(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_speed(owner_id);
insert into history_v5.catalog values ('speed','gas_speed',false);
create table history_v5.gas_cardmaster(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_cardmaster(owner_id);
insert into history_v5.catalog values ('cardMaster','gas_cardmaster',true);
insert into history_v5.gas_cardmaster(id,data) select id,data from history_rc.gas_cardmaster where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'cardMaster',id,data from history_v5.gas_cardmaster;
create table history_v5.gas_cards(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_cards(owner_id);
insert into history_v5.catalog values ('cards','gas_cards',false);
create table history_v5.gas_packs(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_packs(owner_id);
insert into history_v5.catalog values ('packs','gas_packs',false);
create table history_v5.gas_fusion(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_fusion(owner_id);
insert into history_v5.catalog values ('fusion','gas_fusion',false);
create table history_v5.gas_pity(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_pity(owner_id);
insert into history_v5.catalog values ('pity','gas_pity',false);
create table history_v5.gas_missions(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_missions(owner_id);
insert into history_v5.catalog values ('missions','gas_missions',false);
create table history_v5.gas_attendance(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_attendance(owner_id);
insert into history_v5.catalog values ('attendance','gas_attendance',false);
create table history_v5.gas_weekly(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_weekly(owner_id);
insert into history_v5.catalog values ('weekly','gas_weekly',false);
create table history_v5.gas_monthly(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'studentId') stored);
create index on history_v5.gas_monthly(owner_id);
insert into history_v5.catalog values ('monthly','gas_monthly',false);
create table history_v5.gas_audit(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'actorId') stored);
create index on history_v5.gas_audit(owner_id);
insert into history_v5.catalog values ('audit','gas_audit',false);
create table history_v5.gas_deletions(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'actorId') stored);
create index on history_v5.gas_deletions(owner_id);
insert into history_v5.catalog values ('deletions','gas_deletions',false);
create table history_v5.gas_backups(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'actorId') stored);
create index on history_v5.gas_backups(owner_id);
insert into history_v5.catalog values ('backups','gas_backups',false);
create table history_v5.gas_hierarchy(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_hierarchy(owner_id);
insert into history_v5.catalog values ('hierarchy','gas_hierarchy',true);
insert into history_v5.gas_hierarchy(id,data) select id,data from history_rc.gas_hierarchy where namespace='rc-fr42-20260920';
insert into history_v5.settings_checkpoint select 'hierarchy',id,data from history_v5.gas_hierarchy;
create table history_v5.gas_receipts(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (data->>'userId') stored);
create index on history_v5.gas_receipts(owner_id);
insert into history_v5.catalog values ('receipts','gas_receipts',false);
create table history_v5.gas_limits(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_limits(owner_id);
insert into history_v5.catalog values ('limits','gas_limits',false);
create table history_v5.gas_journals(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_journals(owner_id);
insert into history_v5.catalog values ('journals','gas_journals',false);
create table history_v5.gas_migration(id text primary key, data jsonb not null check(jsonb_typeof(data)='object' and data->>'id'=id), owner_id text generated always as (null::text) stored);
create index on history_v5.gas_migration(owner_id);
insert into history_v5.catalog values ('migration','gas_migration',false);
create unique index v5_session_token on history_v5.gas_sessions ((data->>'tokenHash'));
create unique index v5_complete_once on history_v5.gas_records ((data->>'attemptId'));
create unique index v5_request_once on history_v5.gas_receipts(owner_id,(data->>'requestId'));
create unique index v5_open_once on history_v5.gas_packopenings28(owner_id,(data->>'requestId'));
create unique index v5_attendance_once on history_v5.gas_attendance(owner_id,(data->>'unitId'),(data->>'date'));
create unique index v5_mission_once on history_v5.gas_missionclaims(owner_id,(data->>'unitId'),(data->>'runId'),(data->>'missionId'),(data->>'periodKey'));
create index v5_rank on history_v5.gas_records((data->>'mode'),(data->>'official'),((data->>'elapsedMs')::bigint));
alter table history_v5.gas_cards add constraint nonnegative_cards check ((data->>'count')::bigint>=0);
alter table history_v5.gas_cardvariants add constraint nonnegative_variants check ((data->>'count')::bigint>=0);
alter table history_v5.gas_packs add constraint pack_balance check ((data->>'count')::bigint>=0 and jsonb_array_length(data->'guarantees')=(data->>'count')::bigint);
alter table history_v5.gas_shinywallet add constraint nonnegative_shards check ((data->>'shards')::bigint>=0);

-- Reads only the student's indexed partition; configuration has no per-request writes.
create function history_v5.load_scope(p_actor text, p_session text, p_request text, p_action text, p_staff boolean default false)
returns jsonb language plpgsql set search_path='' as $$
declare t record; pred text; rows jsonb; result jsonb='{}'; minimal boolean=p_action in ('student.login','teacher.login');
begin
 for t in select * from history_v5.catalog order by logical_name loop
  pred := case
   when p_staff then 'true'
   when t.logical_name='students' then 'id=$1'
   when t.logical_name='studentScopes3' then 'owner_id=$1'
   when t.logical_name='system' then '(owner_id is null or owner_id=$1)'
   when t.logical_name='receipts' then '(owner_id=$1 and data->>''requestId''=$3)'
   when t.logical_name='limits' then 'id=any(string_to_array($5,'',''))'
   when t.logical_name in ('sessionScopes3','sessionRevocations3') then '(id=$2 or data->>''userId''=$1)'
   when t.shared then 'true'
   when t.logical_name in ('audit','securityEvents','journals','migration','backups','boardSnapshots27') then 'false'
   else 'owner_id=$1' end;
  if minimal and t.logical_name not in ('students','studentScopes3','teachers','teacherPolicies','schools3','system','games','scopedSettings3','sessions','sessionScopes3','sessionRevocations3','limits','receipts') then pred:='false'; end if;
  execute format('select coalesce(jsonb_agg(data),''[]''::jsonb) from history_v5.%I where %s',t.physical_name,pred)
   into rows using p_actor,p_session,p_request,p_action,current_setting('history_v5.limit_ids',true);
  result:=result || jsonb_build_object(t.logical_name,rows);
 end loop;
 return result;
end $$;

-- One INSERT SELECT per affected table; no row-at-a-time network writes.
create function history_v5.write_rows(p_changes jsonb) returns void language plpgsql set search_path='' as $$
declare t record;
begin
 if jsonb_typeof(p_changes)<>'array' then raise exception 'INVALID_CHANGES'; end if;
 if exists(select 1 from jsonb_array_elements(p_changes) c left join history_v5.catalog t on t.logical_name=c->>'table' where t.logical_name is null) then raise exception 'UNKNOWN_TABLE'; end if;
 for t in select distinct c.physical_name,c.logical_name from history_v5.catalog c join jsonb_array_elements(p_changes) x on c.logical_name=x->>'table' loop
  execute format('insert into history_v5.%I(id,data) select x->''row''->>''id'',x->''row'' from jsonb_array_elements($1) x where x->>''table''=$2 on conflict(id) do update set data=excluded.data',t.physical_name) using p_changes,t.logical_name;
 end loop;
end $$;

do $$declare t record; begin
 for t in select tablename from pg_tables where schemaname='history_v5' loop
  execute format('alter table history_v5.%I enable row level security',t.tablename);
  execute format('revoke all on history_v5.%I from public, anon, authenticated, service_role',t.tablename);
  execute format('grant select,insert,update on history_v5.%I to history_v5_worker',t.tablename);
  execute format('create policy worker_access on history_v5.%I to history_v5_worker using(true) with check(true)',t.tablename);
 end loop;
end $$;
revoke all on history_v5.settings_checkpoint from history_v5_worker;
revoke all on all functions in schema history_v5 from public,anon,authenticated,service_role;
grant execute on all functions in schema history_v5 to history_v5_worker;
-- Checkpoints cannot be rewritten by the application runtime.
